apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "neodash.fullname" . }}
  labels:
    {{- include "neodash.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "neodash.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "neodash.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "neodash.serviceAccountName" . }}
      automountServiceAccountToken: false
      # 1. INIT CONTAINER: Creates a writable config.json file

      initContainers:
        - name: init-config
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          # Create an empty file and give it liberal write permissions so the entrypoint can overwrite it
          command:
            - sh
            - -c
            - |
              cp -r /usr/share/nginx/html/* /tmp/nginx-html && \
              cp -r /etc/nginx/templates/* /tmp/nginx-config-templates && \
              cp -r /etc/nginx/conf.d/* /tmp/nginx-conf-d
          volumeMounts:
            - name: nginx-html
              mountPath: /tmp/nginx-html
            - name: nginx-config-templates
              mountPath: /tmp/nginx-config-templates
            - name: nginx-conf-d
              mountPath: /tmp/nginx-conf-d
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
{{/*          command: [ "/bin/sh", "-c" ]*/}}
{{/*          args: [ "sleep 7200" ]*/}}
          {{- with .Values.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
            {{- if ne 5005 (int .Values.service.targetPort) }}
            - name: NGINX_PORT
              value: {{ .Values.service.port | quote }}
            {{- end }}
            {{- if .Values.enable_reader_mode}}
            {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- if .Values.envFromSecrets }}
            {{- range $key, $value := .Values.envFromSecrets }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ $value.secretName }}
                  key: {{ $value.key }}
            {{- end }}
            {{- end }}
            {{- end }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: nginx-html
              mountPath: /usr/share/nginx/html
            - name: nginx-config-templates
              mountPath: /etc/nginx/templates
            - name: nginx-conf-d
              mountPath: /etc/nginx/conf.d
            - name: nginx-cache
              mountPath: /var/cache/nginx
            - name: nginx-run
              mountPath: /var/run
            - name: nginx-tmp
              mountPath: /tmp
      volumes:
        - name: nginx-html
          emptyDir:
            sizeLimit: 100Mi
        - name: nginx-config-templates
          emptyDir:
            sizeLimit: 10Mi
        - name: nginx-conf-d
          emptyDir:
            sizeLimit: 1Mi
        - name: nginx-cache
          emptyDir:
            sizeLimit: 10Mi
        - name: nginx-run
          emptyDir:
            sizeLimit: 10Mi
        - name: nginx-tmp
          emptyDir:
            sizeLimit: 10Mi
{{/*        - name: neodash-config*/}}
{{/*          emptyDir:*/}}
{{/*            sizeLimit: 10Mi*/}}
